
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - service-expose.takumakume.github.io
  resources:
  - serviceexposes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - service-expose.takumakume.github.io
  resources:
  - serviceexposes/finalizers
  verbs:
  - update
- apiGroups:
  - service-expose.takumakume.github.io
  resources:
  - serviceexposes/status
  verbs:
  - get
  - patch
  - update
