apiVersion: service-expose.takumakume.github.io/v1alpha1
kind: ServiceExpose
metadata:
  name: serviceexpose-sample
spec:
  backend:
    service:
      name: service-sample
      port:
        number: 80
  path: /
  pathType: Prefix
  domain: example.com
